### ISSUE TITLE
Why Network Usage always show 0 B?

### ISSUE THREAD

**Issue by kukudemajia** [Kiougar/luci-wrtbwmon#10]
![qq 20170524085333](https://cloud.githubusercontent.com/assets/17118600/26382331/19bdaed4-405e-11e7-8f00-e54debdf3eab.jpg)
luci-wrtbwmon_0.5.1_all.ipk
wrtbwmon_0.36_all.ipk

**Comment by fakuivan** [comment]
Mine works fine, same versions

**Comment by kukudemajia** [comment]
May be  the problem of wrtbwmon.

**Comment by Kiougar** [comment]
Hello @kukudemajia, any updates on this one? Have you found the issue?

**Comment by kukudemajia** [comment]
Thank you very much, I found it was the problem of wrtbwmon.
