### ISSUE TITLE
Not using defined Hostnames

### ISSUE THREAD

**Issue by BradleyDS2** [Kiougar/luci-wrtbwmon#15]
Hi, firstly I'd like to thank you for this project, it is extremely useful and I use it on a daily basis. 

The issue I am having is that in the usage list, several devices are listed by their mac address, even though they have a hostname defined (under Network > Hostnames) making them harder to recognise.

Would it be possible to use either the Hostname specified under Network > Hostnames or the hostname defined when giving a device a static IP (these aren't used either in the Network Usage page)?

**Comment by BradleyDS2** [comment]
Whoops, duplicate.

**Comment by fakuivan** [comment]
Capitalization of mac addresses is usually the problem. For some reason some parts of LuCI think that ``25:22:D0:83:F8:98`` and ``25:22:d0:83:f8:98`` refer to different devices.
