### ISSUE TITLE
[Feature Request] More Auto Update Choices

### ISSUE THREAD

**Issue by BradleyDS2** [Kiougar/luci-wrtbwmon#16]
Would it be possible to have more options for auto update? I like to have it refresh once per second, but to accomplish this I currently use a greasemonkey script to replace the value for Disabled with 1 second or edit the page source with the browser inspector.

On an unrelated note, in LuCI 'Usage Configuration' is not displayed under 'Usage', but under 'Diagnostics'. Would it be possible to group them together?

**Comment by Kiougar** [comment]
I added values from 1-4s in my latest commit and they will be included in the next release.

However, if you can't wait for the release, the easiest and quickest way of changing it would be:
- Open `console` (using your browser's dev tools)
- Type: `interval = 1;`

---

As for the grouping, I think I have a solution in mind but it is not a bulletproof one. LuCI orders links based on a number. I used 60 for `Usage` and 61 for `Usage Configuration`. I think that if I use 60 for both of them they should appear one after the other.
But, in case any other module uses the same number (60) I don't know what would happen :)

I will let you know about the new release so you can test it yourself and then let me know!

**Comment by BradleyDS2** [comment]
Awesome, thank you very much! I really appreciate you making the changes I requested so quickly! :)

As for the ordering, would it be possible to change from using 60, if that's conflicting with the number for Diagnostics? The reason I ask, is because I'm using LEDE Reboot 17.01.4 r3560-79f57e422d (obtained from https://downloads.lede-project.org/releases/17.01.4/targets/mvebu/generic/lede-17.01.4-mvebu-linksys-wrt1900acs-squashfs-factory.img) and Diagnostics is in the stock fw for this version of LEDE, so it isn't simply a module conflict, and it would probably be best to use different numbers for the menu options for Usage and Usage Configuration.

Alternatively, would it be possible to add the configuration option to persist the database to the bottom of the Usage page itself, and remove the 'Usage Configuration page' entirely, as it exists for a single option? Or as another possibility, add an 'Options' tab to the usage page similarly to how LuCI uses separate tabs for 'General Settings', 'Port Forwards', 'Traffic Rules' and 'Custom Rules'.

Sorry if this is asking a bit too much, but I think it would make it look neater and remove the ordering issue entirely.

**Comment by Kiougar** [comment]
I figured it would be a conflict so I changed both of them to 61 (just in case).

I totally agree with you that adding the configuration option inside the Usage page itself (and not have a different configuration page) would be the best solution. Unfortunately this was the easiest and faster way of implementing it (I'm not a Lua nor a LuCI module expert ^_^).

The config page uses the CBI Model that easily creates config pages that all they need to do is write to a config file. Of course it would be doable without it but image the extra effort needed and compare that effort to the actual gain. ;)

**Comment by BradleyDS2** [comment]
Okay, I understand.

Also, I feel really stupid now, because there actually already is a link to the configuration within the usage page. Since you can already access the 'Usage Configuration' from the link in 'Usage' doesn't that render the menu entry for 'Usage Configuration' redundant? Sorry if I'm misunderstanding.

**Comment by Kiougar** [comment]
Well, you can say it is redundant. However, wouldn't the user be confused if he was taken to a page that would not appear in the menu?

Also, another silly (but proven) point is that you missed the link from the usage page, but you didn't miss the link from the menu entry. :)

**Comment by BradleyDS2** [comment]
Honestly, I was actually surprised to see it has its own menu option, and thought it seems out of place since everything else I use in LuCI (which admittedly isn't very much) has a single menu option and a link to the options or a tab to the options from within that page.

Your point about me missing the link on the usage page is valid, but I think the reason I overlooked it is due to the presence of the menu option standing out more due to how out of place it feels to me.

I don't think a user would be confused if the usage options page contains a link redirecting to the usage page up the top like the usage page links to the usage options page, I think that would feel very natural, and is how the rest of LuCI works, but using tabs rather than links.

**Comment by Kiougar** [comment]
Hmm.. Then I think the tab interface of LuCI should be a nice fit here. We have to find a way to implement it though. I'll do my research but If you find anything let me know.

**Comment by BradleyDS2** [comment]
Thanks, I really appreciate it.


It seems that the tabs are just lists using CSS to style them, here's the CSS:
`.tabs, .cbi-tabmenu {
	margin: 0 0 18px;
	padding: 0;
	list-style: none;
	zoom: 1;
}

.tabs:before,
.cbi-tabmenu:before,
.tabs:after,
.cbi-tabmenu:after {
	display: table;
	content: "";
	zoom: 1;
}

.tabs:after, .cbi-tabmenu:after {
	clear: both;
}

.tabs > li, .cbi-tabmenu > li {
	float: left;
}

.tabs > li > a, .cbi-tabmenu > li > a {
	display: block;
}

.tabs,
.cbi-tabmenu {
	border-color: #ddd;
	border-style: solid;
	border-width: 0 0 1px;
}

.tabs > li,
.cbi-tabmenu > li {
	position: relative;
	margin-bottom: -1px;
}

.cbi-tabmenu.map {
	margin: 0;
}

.cbi-tabmenu.map > li {
	font-size: 16.5px;
	font-weight: bold;
}

.cbi-tabcontainer > fieldset.cbi-section[id] > legend {
	display: none;
}

.tabs > li > a,
.cbi-tabmenu > li > a {
	padding: 0 15px;
	margin-right: 2px;
	line-height: 34px;
	border: 1px solid transparent;
	-webkit-border-radius: 4px 4px 0 0;
	-moz-border-radius: 4px 4px 0 0;
	border-radius: 4px 4px 0 0;
}

.tabs > li > a:hover,
.cbi-tabmenu > li > a:hover {
	text-decoration: none;
	background-color: #eee;
	border-color: #eee #eee #ddd;
}

.tabs .active > a, .tabs .active > a:hover,
.cbi-tabmenu .active > a, .cbi-tabmenu .active > a:hover,
.cbi-tab > a:link, .cbi-tab > a:hover {
	color: #808080;
	background-color: #ffffff;
	border: 1px solid #ddd;
	border-bottom-color: transparent;
	cursor: default;
}

.tabs .menu-dropdown, .tabs .dropdown-menu,
.cbi-tabmenu .menu-dropdown, .cbi-tabmenu .dropdown-menu {
	top: 35px;
	border-width: 1px;
	-webkit-border-radius: 0 6px 6px 6px;
	-moz-border-radius: 0 6px 6px 6px;
	border-radius: 0 6px 6px 6px;
}

.tabs a.menu:after, .tabs .dropdown-toggle:after,
.cbi-tabmenu a.menu:after, .cbi-tabmenu .dropdown-toggle:after {
	border-top-color: #999;
	margin-top: 15px;
	margin-left: 5px;
}

.tabs li.open.menu .menu, .tabs .open.dropdown .dropdown-toggle,
.cbi-tabmenu li.open.menu .menu, .cbi-tabmenu .open.dropdown .dropdown-toggle {
	border-color: #999;
}

.tabs li.open a.menu:after, .tabs .dropdown.open .dropdown-toggle:after,
.cbi-tabmenu li.open a.menu:after, .cbi-tabmenu .dropdown.open .dropdown-toggle:after {
	border-top-color: #555;
}

.tab-content > .tab-pane,
.tab-content > div {
	display: none;
}

.tab-content > .active {
	display: block;
}`

Then the HTML looks like this (taken from the firewall page): 
`<ul class="tabs">
    <li class="tabmenu-item-zones active">
        <a href="/cgi-bin/luci/admin/network/firewall/zones">General Settings</a>
    </li>
    <li class="tabmenu-item-forwards ">
        <a href="/cgi-bin/luci/admin/network/firewall/forwards">Port Forwards</a>
    </li>
    <li class="tabmenu-item-rules ">
        <a href="/cgi-bin/luci/admin/network/firewall/rules">Traffic Rules</a>
    </li>
    <li class="tabmenu-item-custom ">
        <a href="/cgi-bin/luci/admin/network/firewall/custom">Custom Rules</a>
    </li>
</ul>`



Here's a screenshot of how the tabs look: https://www.dropbox.com/s/dhh9jkqtgzkzxl9/FW%20Tabs.png

**Comment by Kiougar** [comment]
Moved this to a new issue #17 as this one's title is misleading. Can you please post there what you've found?

**Comment by Kiougar** [comment]
Closed by 3a5b879
