### ISSUE TITLE
Invalid time

### ISSUE THREAD

**Issue by ghost** [Kiougar/luci-wrtbwmon#21]
The wrong time is displayed in the "First Seen" and "Last Seen" columns when any other time zone other than UTC is set. For example, if Asia/Bangkok is written (this is my time zone), then the time in the columns becomes 7 hours more from the present, while the local time in OpenWRT is displayed correctly, according to the time zone.

**Comment by Kiougar** [comment]
Thanks for the issue @Gganazage. It seems I need to take into account the timezone OpenWRT is configured to. Will add it to my TODO list and will close this as soon as it's fixed.
