### ISSUE TITLE
Openwrt 18.06 bootstrap theme squished table

### ISSUE THREAD

**Issue by shemgp** [Kiougar/luci-wrtbwmon#24]
The display of the usage table when running on OpenWRT 18.06 doesn't look nice as tables don't have styles anymore in the new bootstrap theme (looking at the css).
![tables](https://user-images.githubusercontent.com/1734126/43583643-b13fe066-9692-11e8-8235-fa88804d07b6.png)

**Comment by Kiougar** [comment]
Hey @shemgp, thanks for reporting!

I noticed in the release notes of 18.06 this line:

> A GUI bug prevents selecting and scrolling text in the system and kernel log pages. To solve, either upgrade "luci-theme-bootstrap" using opkg or switch to another theme. [fix merged, queued for 18.06.1]

Can you please **upgrade "luci-theme-bootstrap" using opkg** and see if the issue persists?

**Comment by Kiougar** [comment]
@erotavlas85, @shemgp 
I'm currently working on the fix. Doing some cleanup as well.

Expect this to be closed in the coming days with the new release.

Thanks for reporting!

**Comment by erotavlas85** [comment]
Great. Are you planning to release the software into the official repository?

**Comment by Kiougar** [comment]
Yes! Do you have any insights on how should I do it? Never done this before :)

**Comment by erotavlas85** [comment]
I never did before, but the [documentation](https://openwrt.org/docs/guide-developer/helloworld/chapter3) seems straightforward.
