### ISSUE TITLE
install of luci_wrtbwmon fails 

### ISSUE THREAD

**Issue by mikerog25** [Kiougar/luci-wrtbwmon#38]
Hi
This one is a simple fix,  and relates to Issue #34.. Same issue by the looks but was not fixed on instructions   

In the instructions for install  its says 
scp luci_wrtbwmon_*_all.ipk root@192.168.1.1:/tmp/
opkg install /tmp/luci_wrtbwmon_*_all.ipk

but based on download from release directory the ipk comes down as 
luci-wrtbwmon_v0.8.3_all.ipk

Note the '-' after luci ,   and not a '_'

Just failed when running the opkg command,   but was easily found what issue was.

**Comment by Kiougar** [comment]
Fixed by #41
